title: Quo Vadis?
name: "Mostly About AI"
author: Martins Bruveris
twitter_username: BruverisMartins
baseurl: "/"
description: Blog about AI and deep learning
profile_url: "https://martinsbruveris.com"

# Build settings
markdown: kramdown
highlighter: rouge
excerpt_separator: <!--more-->
plugins:
  - jekyll-feed
  - jekyll-archives
  - jekyll-paginate
exclude:
  - Gemfile
  - Gemfile.lock
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
  toc_levels: 1..3

# Pagination
paginate: 5
paginate_path: "/blog/page:num/"

# From jekyll-tagging
# Source: https://github.com/pattex/jekyll-tagging
tag_page_layout: tagpage
tag_page_dir: tag


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
exclude:
  - node_modules/
  - Gemfile
  - Gemfile.lock
  - ideas
  - README.md
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

theme: jekyll-theme-minimal